[tool.poetry]
name = "dlt"
version = "1.8.1"
description = "dlt is an open-source python-first scalable data loading library that does not require any backend to run."
authors = ["dltHub Inc. <services@dlthub.com>"]
maintainers = [ "Marcin Rudolf <marcin@dlthub.com>", "Adrian Brudaru <adrian@dlthub.com>", "Anton Burnashev <anton@dlthub.com>", "David Scharf <david@dlthub.com>" ]
readme = "README.md"
license = "Apache-2.0"
homepage = "https://github.com/dlt-hub"
repository = "https://github.com/dlt-hub/dlt"
classifiers = [
"Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache Software License",
    "Topic :: Software Development :: Libraries",
    "Typing :: Typed",
    "Programming Language :: Python :: 3.12",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: POSIX :: Linux",
    "Operating System :: Microsoft :: Windows",]
keywords = [ "etl" ]
include = [ "LICENSE.txt", "README.md", "dlt/sources/pipeline_templates/.gitignore", "dlt/sources/pipeline_templates/.dlt/config.toml" ]
packages = [
    { include = "dlt" },
]

[tool.poetry.dependencies]
python = ">=3.12,<3.13"
requests = ">=2.26.0"
pendulum = {version = ">=2.1.2"}
simplejson = ">=3.17.5"
PyYAML = ">=5.4.1"
semver = ">=3.0.0"
tomlkit = ">=0.11.3"
typing-extensions = ">=4.8.0"
makefun = ">=1.15.0"
humanize = ">=4.4.0"
orjson = {version = ">=3.10.16,<4", markers="platform_python_implementation != 'PyPy'"}
tenacity = ">=8.0.2"
jsonpath-ng = ">=1.5.3"
fsspec = ">=2022.4.0"
pluggy = ">=1.3.0"
win-precise-time = {version = ">=1.4.2", markers="os_name == 'nt'"}

pyarrow = {version = ">17", optional = true}
duckdb = {version = ">=1.0.0", optional = true}
snowflake-connector-python = {version = ">=3.5.0", optional = true}
adlfs = {version = ">=2024.7.0", optional = true}
pyodbc = {version = ">=4.0.39", optional = true}
sqlalchemy = { version = ">=1.4", optional = true }
paramiko = {version = ">=3.3.0", optional = true}
pywin32 = {version = ">=306", optional = true, platform = "win32"}

[tool.poetry.extras]
parquet = ["pyarrow"]
duckdb = ["duckdb"]
az = ["adlfs"]
sftp = ["paramiko"]
snowflake = ["snowflake-connector-python"]
sql_database = ["sqlalchemy"]

[build-system]
requires = ["poetry-core>=1.0.8"]
build-backend = "poetry.core.masonry.api"
